# Car Price Prediction
#### Using Random Forest Regression

## Importing Libraries

In [1]:
import numpy as np
import pandas as pd

## Importing the Dataset

In [2]:
dataset = pd.read_csv('Car Price.csv')
dataset.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            205 non-null    int64  
 1   symboling         205 non-null    int64  
 2   CarName           205 non-null    object 
 3   fueltype          205 non-null    object 
 4   aspiration        205 non-null    object 
 5   doornumber        205 non-null    object 
 6   carbody           205 non-null    object 
 7   drivewheel        205 non-null    object 
 8   enginelocation    205 non-null    object 
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64  
 14  enginetype        205 non-null    object 
 15  cylindernumber    205 non-null    object 
 16  enginesize        205 non-null    int64  
 1

## Counting the values of Categorial Data

In [4]:
dataset['fueltype'].value_counts()

gas       185
diesel     20
Name: fueltype, dtype: int64

In [5]:
dataset['aspiration'].value_counts()

std      168
turbo     37
Name: aspiration, dtype: int64

In [6]:
dataset['doornumber'].value_counts()

four    115
two      90
Name: doornumber, dtype: int64

In [7]:
dataset['carbody'].value_counts()

sedan          96
hatchback      70
wagon          25
hardtop         8
convertible     6
Name: carbody, dtype: int64

In [8]:
dataset['drivewheel'].value_counts()

fwd    120
rwd     76
4wd      9
Name: drivewheel, dtype: int64

In [9]:
dataset['enginelocation'].value_counts()

front    202
rear       3
Name: enginelocation, dtype: int64

In [10]:
dataset['enginetype'].value_counts()

ohc      148
ohcf      15
ohcv      13
l         12
dohc      12
rotor      4
dohcv      1
Name: enginetype, dtype: int64

In [11]:
dataset['cylindernumber'].value_counts()

four      159
six        24
five       11
eight       5
two         4
three       1
twelve      1
Name: cylindernumber, dtype: int64

In [12]:
dataset['fuelsystem'].value_counts()

mpfi    94
2bbl    66
idi     20
1bbl    11
spdi     9
4bbl     3
mfi      1
spfi     1
Name: fuelsystem, dtype: int64

## Selecting the data(columns)

In [13]:
x = dataset.iloc[:,3:25].values
y = dataset.iloc[:,25].values

In [14]:
print(x)
print(y)

[['gas' 'std' 'two' ... 5000 21 27]
 ['gas' 'std' 'two' ... 5000 21 27]
 ['gas' 'std' 'two' ... 5000 19 26]
 ...
 ['gas' 'std' 'four' ... 5500 18 23]
 ['diesel' 'turbo' 'four' ... 4800 26 27]
 ['gas' 'turbo' 'four' ... 5400 19 25]]
[13495.    16500.    16500.    13950.    17450.    15250.    17710.
 18920.    23875.    17859.167 16430.    16925.    20970.    21105.
 24565.    30760.    41315.    36880.     5151.     6295.     6575.
  5572.     6377.     7957.     6229.     6692.     7609.     8558.
  8921.    12964.     6479.     6855.     5399.     6529.     7129.
  7295.     7295.     7895.     9095.     8845.    10295.    12945.
 10345.     6785.     8916.5    8916.5   11048.    32250.    35550.
 36000.     5195.     6095.     6795.     6695.     7395.    10945.
 11845.    13645.    15645.     8845.     8495.    10595.    10245.
 10795.    11245.    18280.    18344.    25552.    28248.    28176.
 31600.    34184.    35056.    40960.    45400.    16503.     5389.
  6189.     6669.   

## Encoding Variables

In [15]:
from sklearn.preprocessing import LabelEncoder

lb_fueltype = LabelEncoder()
x[:,0] = lb_fueltype.fit_transform(x[:,0])

lb_aspiration = LabelEncoder()
x[:,1] = lb_aspiration.fit_transform(x[:,1])

lb_doornumber = LabelEncoder()
x[:,2] = lb_doornumber.fit_transform(x[:,2])

lb_carbody = LabelEncoder()
x[:,3] = lb_carbody.fit_transform(x[:,3])

lb_drivewheel = LabelEncoder()
x[:,4] = lb_drivewheel.fit_transform(x[:,4])

lb_enginelocation = LabelEncoder()
x[:,5] = lb_enginelocation.fit_transform(x[:,5])

lb_enginetype = LabelEncoder()
x[:,11] = lb_enginetype.fit_transform(x[:,11])

lb_cylindernumber = LabelEncoder()
x[:,12] = lb_cylindernumber.fit_transform(x[:,12])

lb_fuelsystem = LabelEncoder()
x[:,14] = lb_fuelsystem.fit_transform(x[:,14])

In [16]:
x.shape

(205, 22)

## Splitting the dataset into Train & Test

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=1/3, random_state=0)

In [18]:
print(x_train)
print(x_test)

[[1 0 0 ... 5200 31 37]
 [1 0 0 ... 5000 31 38]
 [0 0 0 ... 4800 37 46]
 ...
 [1 1 0 ... 5600 18 24]
 [1 0 0 ... 4750 15 19]
 [1 0 1 ... 4800 24 30]]
[[1 0 1 ... 5000 31 38]
 [1 0 0 ... 5200 19 24]
 [1 0 1 ... 5500 19 25]
 ...
 [1 0 0 ... 5000 25 32]
 [1 0 1 ... 5400 38 43]
 [1 0 0 ... 4800 27 32]]


In [19]:
print(y_train)
print(y_test)

[ 7999.     7395.     7995.     6095.     7053.     7126.    16900.
  7499.    11900.     7463.    13860.    16558.    24565.     8558.
 13200.     8195.    32528.    11048.    13295.    16845.     9258.
 10245.    16500.     8845.     8921.    12764.     6785.    16430.
 12440.    40960.    15985.     7775.     5348.     8249.    13950.
  7349.     5572.     7738.    18950.     5195.    13495.     7299.
 17950.     7799.    11245.     9233.    12945.    28176.    36000.
 35550.     6989.    21485.    21105.     6918.     7957.     9980.
 18620.     6575.    30760.     6669.     9549.     9538.    22470.
 17710.    28248.    14489.     6692.     7198.     9495.     7898.
  6649.    10898.    16925.     7957.    14399.     7295.    13645.
 18280.    16500.     6229.     8238.    10345.    19699.    11850.
 11248.    36880.     9095.    12170.     6695.     7788.    37028.
  7129.     8921.    17075.     6338.     6855.     9639.    34028.
 15690.     5399.     8449.     7775.    22625. 

## Training the model using Random Forest Regression

In [20]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 300, random_state = 0)
regressor.fit(x_train,y_train)

RandomForestRegressor(n_estimators=300, random_state=0)

## Checking the accuracy of the model

In [21]:
accuracy = regressor.score(x_test,y_test)
print(accuracy*100,'%')

90.39909650221148 %


## Predicting the Price using new Data

In [22]:
new_data = ['gas','std','two','convertible','rwd','front',88.6,168.8,64.1,48.8,2548,'dohc','four',130,'mpfi',
            3.47,2.68,9,111,5000,21,27]
new_data[0] = lb_fueltype.transform([new_data[0]])
new_data[1] = lb_aspiration.transform([new_data[1]])
new_data[2] = lb_doornumber.transform([new_data[2]])
new_data[3] = lb_carbody.transform([new_data[3]])
new_data[4] = lb_drivewheel.transform([new_data[4]])
new_data[5] = lb_enginelocation.transform([new_data[5]])
new_data[11] = lb_enginetype.transform([new_data[11]])
new_data[12] = lb_cylindernumber.transform([new_data[12]])
new_data[14] = lb_fuelsystem.transform([new_data[14]])

In [23]:
print(new_data)
regressor.predict([new_data])

[array([1]), array([0]), array([1]), array([0]), array([2]), array([0]), 88.6, 168.8, 64.1, 48.8, 2548, array([0]), array([2]), 130, array([5]), 3.47, 2.68, 9, 111, 5000, 21, 27]


array([14433.45611111])